[project]
name = "filespace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crispy-bootstrap5>=2026.3",
    "django>=6.0.4",
    "django-axes[ipware]>=8.3.1",
    "django-crispy-forms>=2.6",
    "python-dotenv>=1.2.2",
]

[dependency-groups]
dev = [
    "gunicorn>=25.3.0",
    "psycopg2-binary>=2.9.12",
]
