# Generated by Django 6.0.4 on 2026-04-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='full_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
