# Generated by Django 6.0.4 on 2026-04-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_full_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
